AP_InternalError: only panic in SITL if debug enabled
a user recently had a flow of control panic in quadplane in
cygwin/missionplanner SITL. The panic this caused means we don't get
logging information on what line of code was triggered

the panic in SITL for internal errors is only useful if you have debug
information and can then attach a debugger. Without debug information
it is much better to behave the same as a real vehicle and report an
internal error (with line number)